language: php

sudo: false

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7

before_install:
  - composer self-update
  - composer install --no-interaction

script:
- |
  if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]] ; then
    phpunit --coverage-clover=coverage.clover
  else
    phpunit
  fi
after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1

notifications:
  slack:
    rooms:
      - ironbounddesigns:fXMBlqSr9vvDBiwetLNm9ctD#general

    on_success: change
    on_failure: always
    on_start: never
  email: false